name: Testes Regressivos - PR
on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/formated-report/"

      - name: Enviar Notificação Slack - Sucesso
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNELL: testes-github-devops
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.pngall.com/wp-content/uploads/2016/07/Success-PNG-Image.png
          SLACK_MESSAGE: 'Testes do PR executado com sucesso! :white_check_mark:'
          SLACK_TITLE: 'Testes do PR executado com sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar Notificação Slack - Falha
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNELL: testes-github-devops
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://w7.pngwing.com/pngs/349/105/png-transparent-false-error-missing-absent-x-red-cross-letter-circle-gui.png
          SLACK_MESSAGE: 'Erro ao executar testes do PR ! :fire:'
          SLACK_TITLE: 'Erro ao executar testes do PR! :fire:'
          SLACK_USERNAME: ERRO